package compiler

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/format"
	goparser "go/parser"
	"go/token"
	"io/fs"
	"maps"
	"os"
	"slices"
	"strconv"
)

// PreludeStubs generates prelude/go's stub file (decision 154): every declaration the generated program would hold
// that prelude/go names but does not declare, with `panic(0)` for bodies, so `go vet -tags rb2go_prelude ./prelude/go`
// and gopls can type-check the helpers.
func PreludeStubs(ctx context.Context, preludeFS fs.FS) ([]byte, error) {
	// ponytail: formatGo reads the env; an options field would need plumbing through emitProgram.
	_ = os.Setenv("RB2GO_NO_PRUNE", "1")
	defer func() { _ = os.Unsetenv("RB2GO_NO_PRUNE") }()
	opts := options{allLibs: true}
	src, err := compile(ctx, preludeFS, []Source{{Name: "main.rb", Src: []byte("puts 1\n")}}, &opts)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	f, err := goparser.ParseFile(fset, "main.go", src, 0)
	if err != nil {
		return nil, fmt.Errorf("parse generated program: %w", err)
	}
	declared, refs, err := preludeGoNames(preludeFS)
	if err != nil {
		return nil, err
	}
	byName, methods := indexDecls(f)
	kept := map[ast.Decl]bool{}
	var out []ast.Decl
	seen := map[string]bool{}
	work := slices.Sorted(maps.Keys(refs))
	keep := func(d ast.Decl) {
		if kept[d] {
			return
		}
		kept[d] = true
		stubBody(d)
		out = append(out, d)
		ast.Inspect(d, func(n ast.Node) bool {
			if id, ok := n.(*ast.Ident); ok && !seen[id.Name] {
				work = append(work, id.Name)
			}
			return true
		})
	}
	for len(work) > 0 {
		name := work[0]
		work = work[1:]
		if seen[name] || declared[name] {
			continue
		}
		seen[name] = true
		for _, d := range byName[name] {
			keep(d)
		}
		for _, m := range methods[name] {
			if !declared[name+"."+m.Name.Name] && !growsReceiver(m) {
				keep(m)
			}
		}
	}
	return printStubs(fset, out)
}

// indexDecls maps a program's top-level names to their declarations (a const group whole, for iota; other groups
// split per spec) and its methods by receiver type. main and init are left out.
func indexDecls(f *ast.File) (byName map[string][]ast.Decl, methods map[string][]*ast.FuncDecl) {
	byName, methods = map[string][]ast.Decl{}, map[string][]*ast.FuncDecl{}
	add := func(d ast.Decl, s ast.Spec) {
		switch s := s.(type) {
		case *ast.TypeSpec:
			byName[s.Name.Name] = append(byName[s.Name.Name], d)
		case *ast.ValueSpec:
			for _, n := range s.Names {
				byName[n.Name] = append(byName[n.Name], d)
			}
		}
	}
	for _, d := range f.Decls {
		switch d := d.(type) {
		case *ast.FuncDecl:
			if d.Recv != nil {
				r := recvName(d.Recv.List[0].Type)
				methods[r] = append(methods[r], d)
			} else if d.Name.Name != "main" && d.Name.Name != "init" {
				byName[d.Name.Name] = append(byName[d.Name.Name], d)
			}
		case *ast.GenDecl:
			for _, s := range d.Specs {
				if d.Tok == token.CONST {
					add(d, s)
				} else {
					add(&ast.GenDecl{Tok: d.Tok, Specs: []ast.Spec{s}}, s)
				}
			}
		}
	}
	return byName, methods
}

// stubBody replaces a function's body with panic(0) and drops its doc comment.
func stubBody(d ast.Decl) {
	fd, ok := d.(*ast.FuncDecl)
	if !ok {
		return
	}
	fd.Body = &ast.BlockStmt{List: []ast.Stmt{&ast.ExprStmt{X: &ast.CallExpr{
		Fun: ast.NewIdent("panic"), Args: []ast.Expr{&ast.BasicLit{Kind: token.INT, Value: "0"}},
	}}}}
	fd.Doc = nil
}

// printStubs renders the kept declarations as a gofmt-clean file under the rb2go_prelude tag, importing the std
// packages they name.
func printStubs(fset *token.FileSet, decls []ast.Decl) ([]byte, error) {
	used := map[string]bool{}
	for _, d := range decls {
		ast.Inspect(d, func(n ast.Node) bool {
			if sel, ok := n.(*ast.SelectorExpr); ok {
				if id, ok := sel.X.(*ast.Ident); ok && id.Obj == nil && stdImports[id.Name] != "" {
					used[stdImports[id.Name]] = true
				}
			}
			return true
		})
	}
	var b bytes.Buffer
	b.WriteString("//go:build rb2go_prelude\n\n// Code generated by `rb2go stubs`; DO NOT EDIT.\n// What generated code declares and prelude/go names, bodies replaced by panic(0): enough for gopls and go vet (decision 154).\n\npackage prelude\n\nimport (\n")
	for _, p := range slices.Sorted(maps.Keys(used)) {
		b.WriteString("\t" + strconv.Quote(p) + "\n")
	}
	b.WriteString(")\n\n")
	for _, d := range decls {
		err := format.Node(&b, fset, d)
		if err != nil {
			return nil, fmt.Errorf("print stub: %w", err)
		}
		b.WriteString("\n\n")
	}
	res, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format stubs: %w", err)
	}
	return res, nil
}

// preludeGoNames parses prelude/go/*.go: what they declare at top level (functions, types, values, and methods as
// "Recv.Name"), and every identifier they mention.
func preludeGoNames(preludeFS fs.FS) (declared, refs map[string]bool, err error) {
	declared, refs = map[string]bool{}, map[string]bool{}
	names, err := fs.Glob(preludeFS, "prelude/go/*.go")
	if err != nil {
		return nil, nil, fmt.Errorf("prelude/go: %w", err)
	}
	fset := token.NewFileSet()
	for _, name := range names {
		src, err := fs.ReadFile(preludeFS, name)
		if err != nil {
			return nil, nil, fmt.Errorf("prelude/go: %w", err)
		}
		f, err := goparser.ParseFile(fset, name, src, 0)
		if err != nil {
			return nil, nil, fmt.Errorf("%s: %w", name, err)
		}
		for _, d := range f.Decls {
			switch d := d.(type) {
			case *ast.FuncDecl:
				if d.Recv == nil {
					declared[d.Name.Name] = true
				} else {
					declared[recvName(d.Recv.List[0].Type)+"."+d.Name.Name] = true
				}
			case *ast.GenDecl:
				for _, s := range d.Specs {
					switch s := s.(type) {
					case *ast.TypeSpec:
						declared[s.Name.Name] = true
					case *ast.ValueSpec:
						for _, n := range s.Names {
							declared[n.Name] = true
						}
					}
				}
			}
		}
		ast.Inspect(f, func(n ast.Node) bool {
			if id, ok := n.(*ast.Ident); ok {
				refs[id.Name] = true
			}
			return true
		})
	}
	return declared, refs, nil
}

// growsReceiver reports a generic method whose signature names its own receiver type instantiated with something
// other than the receiver's bare type parameters (`Enumerator_Lazy[E].WithIndex() *Enumerator_Lazy[Tuple2[E, Integer]]`):
// `go build` rejects the stub as an instantiation cycle. Programs never reach them; the pruner drops them.
func growsReceiver(m *ast.FuncDecl) bool {
	if m.Recv == nil {
		return false
	}
	recv := m.Recv.List[0].Type
	if s, ok := recv.(*ast.StarExpr); ok {
		recv = s.X
	}
	var base string
	params := map[string]bool{}
	switch r := recv.(type) {
	case *ast.IndexExpr:
		base = recvName(r)
		if id, ok := r.Index.(*ast.Ident); ok {
			params[id.Name] = true
		}
	case *ast.IndexListExpr:
		base = recvName(r)
		for _, i := range r.Indices {
			if id, ok := i.(*ast.Ident); ok {
				params[id.Name] = true
			}
		}
	default:
		return false
	}
	grows := false
	ast.Inspect(m.Type, func(n ast.Node) bool {
		var x ast.Expr
		var args []ast.Expr
		switch e := n.(type) {
		case *ast.IndexExpr:
			x, args = e.X, []ast.Expr{e.Index}
		case *ast.IndexListExpr:
			x, args = e.X, e.Indices
		default:
			return true
		}
		if id, ok := x.(*ast.Ident); ok && id.Name == base {
			for _, a := range args {
				if id, ok := a.(*ast.Ident); !ok || !params[id.Name] {
					grows = true
				}
			}
		}
		return true
	})
	return grows
}
