# prelude.rb
# rbs_inline: enabled
#
# The core library, compiled by the same transpiler as user code. It reopens
# core classes, so it never runs on MRI. Only `%x{}` leaves drop into Go.
# Each file is pulled in with require_relative; order matters only for the
# order of the emitted Go.

require_relative "prelude/runtime"
require_relative "prelude/object"
require_relative "prelude/module"
require_relative "prelude/struct"
require_relative "prelude/dynamic"
require_relative "prelude/boolean"
require_relative "prelude/integer"
require_relative "prelude/float"
require_relative "prelude/math"
require_relative "prelude/rational"
require_relative "prelude/random"
require_relative "prelude/complex"
require_relative "prelude/string"
require_relative "prelude/symbol"
require_relative "prelude/regexp"
require_relative "prelude/enumerable"
require_relative "prelude/array"
require_relative "prelude/enumerator"
require_relative "prelude/range"
require_relative "prelude/hash"
require_relative "prelude/set"
require_relative "prelude/time"
require_relative "prelude/date"
require_relative "prelude/exception"
require_relative "prelude/json"
require_relative "prelude/stringio"
require_relative "prelude/io"
require_relative "prelude/file"
require_relative "prelude/fileutils"
require_relative "prelude/tempfile"
require_relative "prelude/pathname"
require_relative "prelude/find"
require_relative "prelude/logger"
require_relative "prelude/base64"
require_relative "prelude/digest"
require_relative "prelude/zlib"
require_relative "prelude/securerandom"
require_relative "prelude/cgi"
require_relative "prelude/strscan"
require_relative "prelude/shellwords"
require_relative "prelude/abbrev"
require_relative "prelude/benchmark"
require_relative "prelude/csv"
require_relative "prelude/singleton"
require_relative "prelude/thread"
require_relative "prelude/queue"
require_relative "prelude/ractor"
require_relative "prelude/etc"
require_relative "prelude/timeout"
require_relative "prelude/uri"
require_relative "prelude/ipaddr"
require_relative "prelude/net_http"
require_relative "prelude/webrick"
require_relative "prelude/open_uri"
require_relative "prelude/socket"
require_relative "prelude/process"
require_relative "prelude/open3"
require_relative "prelude/tsort"
require_relative "prelude/observable"
require_relative "prelude/monitor"
require_relative "prelude/weakref"
require_relative "prelude/erb"
require_relative "prelude/bigdecimal"
require_relative "prelude/pp"
require_relative "prelude/forwardable"
require_relative "prelude/optparse"
require_relative "prelude/minitest"
require_relative "prelude/rexml"
require_relative "prelude/ostruct"
require_relative "prelude/delegate"
